name: Slack Post Counter

on:
  schedule:
    # 毎週木曜 16:00 (JST) → 木曜 07:00 (UTC)
    - cron: '0 7 * * 4'
  workflow_dispatch:  # 手動実行も可能にする

jobs:
  run-counter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Slack Post Counter
        run: |
          python main.py \
            --token "${{ secrets.SLACK_TOKEN }}" \
            --channel "${{ secrets.SLACK_CHANNEL_ID }}" \
            --days 7